# Generated by Django 5.1.7 on 2025-03-25 01:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripción del Proyecto')),
                ('estado', models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('en_progreso', 'En Progreso'), ('en_pausa', 'En Pausa'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='no_iniciado', max_length=20, verbose_name='Estado del Proyecto')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto del Proyecto')),
                ('recursos', models.TextField(blank=True, null=True, verbose_name='Recursos del Proyecto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('integrantes', models.ManyToManyField(blank=True, related_name='proyectos_integrante', to=settings.AUTH_USER_MODEL, verbose_name='Integrantes del Proyecto')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
