# Generated by Django 5.1.7 on 2025-04-05 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_meetingcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('pasos_reproducir', models.TextField(blank=True, null=True, verbose_name='Pasos para Reproducir')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critico', 'Crítico')], default='media', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('reportado', 'Reportado'), ('asignado', 'Asignado'), ('en_progreso', 'En Progreso'), ('resuelto', 'Resuelto'), ('verificado', 'Verificado'), ('cerrado', 'Cerrado'), ('rechazado', 'Rechazado')], default='reportado', max_length=15, verbose_name='Estado')),
                ('tipo', models.CharField(choices=[('error', 'Error'), ('funcional', 'Funcionalidad'), ('seguridad', 'Seguridad'), ('rendimiento', 'Rendimiento'), ('usabilidad', 'Usabilidad'), ('otros', 'Otros')], default='error', max_length=15, verbose_name='Tipo de Bug')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_tope', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Tope')),
                ('fecha_resuelto', models.DateTimeField(blank=True, null=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='coreapp.proyecto', verbose_name='Proyecto')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs_reportados', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs_resueltos', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs_verificados', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Bug',
                'verbose_name_plural': 'Bugs',
                'ordering': ['-prioridad', 'fecha_tope'],
            },
        ),
    ]
