# Generated by Django 5.1.7 on 2025-04-05 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('tipo', models.CharField(choices=[('expediente', 'Expediente del Proyecto'), ('requisitos', 'Descripción de Requisitos'), ('casos_uso', 'Diagramas de Casos de Uso'), ('modelado', 'Modelado del Negocio'), ('diseno', 'Diseño del Sistema'), ('manual', 'Manuales de Usuario'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='proyectos/documentos/', verbose_name='Archivo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_subido', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_proyecto', to='coreapp.proyecto', verbose_name='Proyecto')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subido'],
            },
        ),
    ]
