# Generated by Django 5.1.7 on 2025-04-05 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={},
        ),
        migrations.RemoveField(
            model_name='documento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='fecha_actualizado',
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documento',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_proyecto', to='coreapp.proyecto'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='subido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('CT', 'Contrato'), ('FC', 'Factura'), ('IN', 'Informe'), ('DS', 'Diseño'), ('OT', 'Otro')], default='OT', max_length=2),
        ),
    ]
