# Generated by Django 5.1.7 on 2025-04-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_alter_documento_options_remove_documento_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='titulo_corto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Título corto'),
        ),
    ]
