# Generated by Django 5.1.7 on 2025-04-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_tarea_titulo_corto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('RT', 'Requisitos'), ('PB', 'Pruebas'), ('IN', 'Informe'), ('DS', 'Diseño'), ('OT', 'Otro')], default='OT', max_length=2),
        ),
    ]
